spring.application.name=RestCrudApp1

spring.datasource.url =jdbc:mysql://localhost:3306/RestCurd

spring.datasource.username =root

spring.datasource.password =Sabitha@123


server.servlet.context-path=/restApp

server.port=8081